### ISSUE TITLE
Delete Car Confirmation and Redirect

### ISSUE THREAD

**Issue by rodrigorgeronimo** [fabiociconi/FinalProjectCentennial#22]
The customer is able to delete a car. However, the system does not show a confirmation message and the user is not redirected to the cars' list page.

![delete car bug](https://user-images.githubusercontent.com/28652586/37262418-6b833530-2579-11e8-954e-929e46943d1e.png)

- [ ] Confirmation message is not showing up after deleting a car
- [ ] User is not redirected after deleting a car

**Comment by marviobezerra** [comment]
Done

**Comment by rodrigorgeronimo** [comment]
Issue fixed.
