### ISSUE TITLE
"Remember me" box does not work

### ISSUE THREAD

**Issue by rodrigorgeronimo** [fabiociconi/FinalProjectCentennial#23]
Customer/Workshop ticks "Remember me" box on the Login Page. However, when the user tries to authenticate again, email and password are not automatically filled.

![image](https://user-images.githubusercontent.com/28652586/37263382-4c67b478-257e-11e8-8390-d79bcdfa6e2b.png)

- [ ] "Remember me" box

**Comment by marviobezerra** [comment]
Done
