### ISSUE TITLE
Workshop cannot see dashboard and profile page

### ISSUE THREAD

**Issue by rodrigorgeronimo** [fabiociconi/FinalProjectCentennial#24]
A Workshop can sign up on the system, but it cannot see its own profile page and dashboard.

![image](https://user-images.githubusercontent.com/28652586/37263618-53d81724-257f-11e8-8757-4e0bb60d30e2.png)

The user cannot see:

- [x] Workshop Dashboard
- [x] Workshop Profile Page

**Comment by marviobezerra** [comment]
Done

**Comment by rodrigorgeronimo** [comment]
Issue fixed.
