### ISSUE TITLE
No Message Errors on Sign Up Page

### ISSUE THREAD

**Issue by rodrigorgeronimo** [fabiociconi/FinalProjectCentennial#25]
On Sign Up Page, when Customer/Workshop does not fill all required fields, the password does not match, or a duplicated (or invalid) email is typed, the system is not showing any kind of message to alert the user about this errors.

![image](https://user-images.githubusercontent.com/28652586/37264016-81fd0c3e-2581-11e8-8286-ae3669cda967.png)

Show a message when:

- [ ] User does not fill all required fields
- [ ] Password does not match 
- [ ] Email typed is duplicated in the system
- [ ] Email is invalid

**Comment by marviobezerra** [comment]
Done

**Comment by marviobezerra** [comment]
Done
